
name: Build without test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    uses: Roadhog360/Hog-Actions-Workflows/.github/workflows/build-without-test.yml@master
    secrets: inherit
